security:
    encoders:
        App\Entity\User: auto
    providers:
        db:
            entity:
                class: App:User
                property: username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern: ^/login
            stateless: true
            anonymous: true
            json_login:
                check_path: /login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false
                username_path: username
                password_path: password
        register:
            pattern: ^/register
            stateless: true
            anonymous: true
        api:
            pattern: ^/
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
                    - App\Security\Guard\PullTokenAuthenticator
                entry_point: lexik_jwt_authentication.jwt_token_authenticator

    access_control:
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/reset-password-request, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/me/?$, roles: ROLE_USER }
        - { path: ^/pull/, roles: ROLE_PULL }
        - { path: ^/, roles: ROLE_USER, methods: [DELETE, POST, PUT] }
        - { path: ^/organizations/?$, roles: ROLE_USER, methods: [GET] }
