version: '3.8'

services:
  db:
    container_name: dentest_api_db
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dentest
  php-fpm:
    container_name: dentest_api_php_fpm
    build:
      context: ./php-fpm
    depends_on:
      - db
    environment:
      APP_ENV: dev
      DATABASE_URL: postgresql://postgres:password@db:5432/dentest
      ALLOWED_ORIGIN: http://localhost:3000
    volumes:
      - ../:/var/www
  nginx:
    container_name: dentest_api_nginx
    build:
      context: ./nginx
    volumes:
      - ../:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8000:80"
      #- "443:443"
